site_name: "Cuaderno Ingeniería de Proteínas"
site_author: "Francisco de Borja Campuzano Jiménez"
site_description: "Cuaderno de actividades de Francisco Campuzano Jiménez de la asignatura de Ingeniería de Proteínas del curso 2021-2022 sobre la proteína Human glutaminyl cyclase (hQC)"
site_url: "https://currocam.github.io/biotools_hQC/"
repo_name: "biotools_hQC"
repo_url: "https://github.com/currocam/biotools_hQC"
copyright: Copyleft - CC BY-NC 4.0 - Francisco Campuzano Jiménez

theme:
  favicon: "images/logoasl.png"
  features:
    - navigation.instant
  icon:
    logo: material/git
  name: "material"
  language: "es"
  palette:
    scheme: slate

plugins:
  - awesome-pages
  - git-revision-date-localized:
      type: date
  - search
  - bibtex:
      bib_file: "refs.bib"
      cite_style: "pandoc"

extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/currocam"
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/currocam"

markdown_extensions:
  - admonition: ~
  - attr_list: ~
  - codehilite:
      guess_lang: false
      linenums: false
  - def_list: ~
  - tables
  - footnotes: ~
  - toc:
      permalink: true
  - pymdownx.keys: ~
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true 

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tablesort.js
